### ISSUE TITLE
Newest OBS pipewire is gone

### ISSUE THREAD

**Issue by ryzendew** [Nobara-Project/rpm-sources#55]
[2024-06-13 07-27-57.txt](https://github.com/user-attachments/files/15818046/2024-06-13.07-27-57.txt)

here is the log 

i have fixed it on my end by replacing the broken `linux-pipewire.so` in `/usr/lib64/obs-plugins/`
with one that works

**Comment by LionHeartP** [comment]
Should be fixed with 882962c

**Comment by GloriousEggroll** [comment]
> Should be fixed with [882962c](https://github.com/Nobara-Project/rpm-sources/commit/882962cdd328a5b36f913638b348155529575317)

thats just a workaround. we had to disable the pipewire audio capture plugin until its rebased:
https://github.com/obsproject/obs-studio/pull/6207

**Comment by GloriousEggroll** [comment]
> @GloriousEggroll Rebased 3 days ago

I tried the rebase and it still failed.

I've worked around the issue by just making it a separate plugin package:

https://github.com/Nobara-Project/rpm-sources/commit/e120c6692b496d2d924c733de9c2df7ff2f18947
